[project]
name = "workshop-dlt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[duckdb]>=1.6.1",
    "pandas>=2.2.3",
]
