[project]
name = "05-batch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.0"
dependencies = [
    "jupyter>=1.1.1",
    "pyspark==3.3.2",
]
